{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wj.gradle.plugins",
    "module": "manifestplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "manifestplugin-1.0.0.jar",
          "url": "manifestplugin-1.0.0.jar",
          "size": 18675,
          "sha512": "29329f42a8d0e8b58d8e090b0cadb8e740e52020914ca0969cfd8f3bd600a3d0c9073fde0e07437d8b4353a427c0e044607b2e0e18b6825464fb16ddff76814e",
          "sha256": "4856d2c76b1ab4934f818858ab8c280b2be587df48d214a0db21fd2e6e87ec30",
          "sha1": "a33ae66689a1dcf84e6aa07431817b3d62f3801d",
          "md5": "2cb2c34defc4d91f3c0ef3e3620602d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "manifestplugin-1.0.0.jar",
          "url": "manifestplugin-1.0.0.jar",
          "size": 18675,
          "sha512": "29329f42a8d0e8b58d8e090b0cadb8e740e52020914ca0969cfd8f3bd600a3d0c9073fde0e07437d8b4353a427c0e044607b2e0e18b6825464fb16ddff76814e",
          "sha256": "4856d2c76b1ab4934f818858ab8c280b2be587df48d214a0db21fd2e6e87ec30",
          "sha1": "a33ae66689a1dcf84e6aa07431817b3d62f3801d",
          "md5": "2cb2c34defc4d91f3c0ef3e3620602d9"
        }
      ]
    }
  ]
}
