{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wj.gradle.plugins",
    "module": "manifestplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "manifestplugin-1.0.0.jar",
          "url": "manifestplugin-1.0.0.jar",
          "size": 17179,
          "sha512": "f741798f94338c998fbd59086ed7f39fbd9baca8c8636c1c1e4e436d2dda8c443f8eb7f135ff8826ad8608a6931cb3682f4912b11a5e2ef30f032ba11467954b",
          "sha256": "dfeebbc44eb56bb685d71beba61c5e7be02989f62045cb4b8495f06ee1183462",
          "sha1": "c17187d176098bbb438b793f0bd799b955ea217b",
          "md5": "cba80eca8be1c82646fa3c2c2cba86b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "manifestplugin-1.0.0.jar",
          "url": "manifestplugin-1.0.0.jar",
          "size": 17179,
          "sha512": "f741798f94338c998fbd59086ed7f39fbd9baca8c8636c1c1e4e436d2dda8c443f8eb7f135ff8826ad8608a6931cb3682f4912b11a5e2ef30f032ba11467954b",
          "sha256": "dfeebbc44eb56bb685d71beba61c5e7be02989f62045cb4b8495f06ee1183462",
          "sha1": "c17187d176098bbb438b793f0bd799b955ea217b",
          "md5": "cba80eca8be1c82646fa3c2c2cba86b6"
        }
      ]
    }
  ]
}
